**Scalar Values:** To define a scalar in python, use " $X = value$ "

In [3]:
x = 15
print(x)

15


**Vectors:** A vector in python is a data type known as a list. To define a vector, use "[  ]" around some numbers.

In [9]:
x = [15, 36, 423.24]
print(x)

[15, 36, 423.24]


In [16]:
#Python also supports creating arrays
# of a defined length
x = [None]*5
x[0] = 1
x[1] = 1
x[2] = 2
x[3] = 3
x[4] = 5
print(x)

[1, 1, 2, 3, 5]


In [17]:
#and you can append to a list with x.append(item)
x.append(8)
print(x)

[1, 1, 2, 3, 5, 8]


In [20]:
#To index into a list, you use a bracket
# behind the variable to select the index

#grab the first item
first_item = x[0]
print(first_item)
#grab last item
last_item = x[5]
print(last_item)

1
8


**Matrices:**  Given that a matrix is a list of vectors, a matrix in python is just a list of vectors (which are lists of items)

In [21]:
x1 = [1, 2]
x2 = [3, 4]
x = [x1, x2]
print(x)

[[1, 2], [3, 4]]


In [24]:
#matrices can also be instantiated like lists
x = [[5,6], [3,4]]
print(x)
x.append([1,2])
print(x)

[[5, 6], [3, 4]]
[[5, 6], [3, 4], [1, 2]]


*Note:*  In all python libraries, matrices are defined in terms of their rows. So the matrix above is 3x2 matrix, as it has three items, each of size two.

In [25]:
#to grab a row, use the same indexing as a list
x[0]

[5, 6]

In [29]:
#To grab a scalar, index into the row,
# and then into the item

#grab 6, the 2nd item in the first row
first_row = x[0]
six = first_row[1]
print(six)

#The separation above is for clarity,
# you can do it in one line
five = x[0][0]
print(five)



6
5


**Numpy:** The reason we all do ML in python :D

In [30]:
#imports
import numpy as np

To cast from python lists to a numpy matrix, you can use

**np.asarray(matrix)** or **np.array(matrix)**

In [33]:
numpy_x = np.asarray(x)
print(numpy_x)

[[5 6]
 [3 4]
 [1 2]]


**Relevant commands**

**x.shape()** - returns the shape of the matrix as a tuple

**np.zeros((shape))** - takes in a tuple shape, returns a matrix of zeros

**np.eye(shape)** - returns an identity matrix of shape * shape

**x.dot(y)** - returns the dot product of <x,y> - this is matrix multiplication.

This is abbreviated as "x @ y"

**NOTE: DO NOT USE X * Y for matrix multiplication.** 
This will do an element-wise operation and your results won't make sense

**x + y** - Exactly what you would expect.

**np.linalg.inv(x)** - returns the inverse, errors if mat is singular


In [36]:
#Lets try them out!
x = [[1,2], [3,4]]
x = np.asarray(x)

#y is the identity
y = np.eye(2)

In [41]:
print("x:")
print(x)
print("\ny:")
print(y)

x:
[[1 2]
 [3 4]]

y:
[[1. 0.]
 [0. 1.]]


In [42]:
print(x.shape)

(2, 2)


In [49]:
print(y.shape)

(2, 2)


In [50]:
#x * y - x @ identity should = x
z = x @ y
print(z)

[[1. 2.]
 [3. 4.]]


**BLAS Tricks**

In [54]:
#lets compare equality - what will this do?
k = (z == x)

In [55]:
print(k)

[[ True  True]
 [ True  True]]


In [57]:
#These comparisons work for other ops as well:
x = np.asarray([[1, 2], [-1, -2]])
print(x)

[[ 1  2]
 [-1 -2]]


In [59]:
#greater than
print(x > 0)

[[ True  True]
 [False False]]


In [61]:
#modulus - check if even
print(x % 2 == 0)

[[False  True]
 [False  True]]


In [64]:
#These truthy matrices can be used for masking
# very important for some operations such as ReLU
print (x * (x > 0))

[[1 2]
 [0 0]]


In [66]:
#and the inverse, just for fun
print(np.linalg.inv(x))

LinAlgError: Singular matrix

In [68]:
#lets modify x to work
x[1][0] = 2
print(x)

[[ 1  2]
 [ 2 -2]]


In [71]:
x_inv = np.linalg.inv(x)
print(x_inv)

[[ 0.33333333  0.33333333]
 [ 0.33333333 -0.16666667]]


In [73]:
#this should be the identity, +/- float errors.
print(x @ x_inv)

[[1.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00]]
